from setuptools import setup, find_packages

setup(
    name="one_dm",
    version="0.1.0",
    description="One-DM: A Diffusion Model for Text Style Transfer with One Example",
    author="Original Authors & Contributors",
    author_email="example@example.com",
    url="https://github.com/your-username/One-DM",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.8",
    install_requires=[
        "torch>=1.13.0",
        "torchvision>=0.14.0",
        "diffusers>=0.8.0",
        "opencv-python",
        "einops",
        "Pillow",
        "numpy",
        "scipy",
        "tqdm",
        "wandb",
        "tensorboard",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
) 